# Site settings
title: wscontest - Tools for the Wikisouce’s Anniversary Proofreading Contest
tag_text: wscontest
description: wscontest is a collection of tools for running the Wikisouce’s Anniversary Proofreading Contest in your local Wikisource

# Build settings
markdown: kramdown
exclude: ["README.md"]
sass:
  style: compressed
